from Attack_MAS.memory import STM
from Attack_MAS.simple_agent import SimpleAgent,Model
from Attack_MAS.prompts import get_S1_AGENT_SYS_PROMPT,get_S2_AGENT_SYS_PROMPT,get_S3_AGENT_SYS_PROMPT
import json
import re

# Answer verification function

def response_verification_S1(llm_response: str):
    """
    Extract a JSON object from the LLM output and validate its fields and field value types.

    Validation includes:
    1. Whether a JSON object can be parsed.
    2. Must contain the following four fields:
        - dialogue_stage: str
        - requested_information: list
        - current_customer_requested_action: str
        - factual_summary: str
    3. Only types are validated; field contents are not checked.

    Returns:
        is_correct (bool): Whether validation passes.
        result (dict): The parsed dict if successful; otherwise {}.
    """
    is_correct = False
    result = {}

    if not isinstance(llm_response, str):
        return is_correct, result

    text = llm_response.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)

    match = re.search(r"\{.*\}", text, flags=re.DOTALL)
    if not match:
        return is_correct, result

    json_str = match.group(0)

    try:
        data = json.loads(json_str)
    except json.JSONDecodeError:
        return is_correct, result

    if not isinstance(data, dict):
        return is_correct, result

    required_fields = {
        "dialogue_stage": str,
        "requested_information": list,
        "current_customer_requested_action": str,
        "factual_summary": str,
    }

    if set(data.keys()) != set(required_fields.keys()):
        return is_correct, result

    for field, field_type in required_fields.items():
        if not isinstance(data[field], field_type):
            return is_correct, result

    is_correct = True
    result = data
    return is_correct, result

def response_verification_S2(llm_response: str):
    is_correct = False
    result = {}

    match = re.search(r"\{.*\}", llm_response, re.DOTALL)
    if not match:
        return is_correct, result

    json_str = match.group(0)

    try:
        result = json.loads(json_str)
    except json.JSONDecodeError:
        return is_correct, {}

    required_fields = [
        "final_customer_response_generation_steps",
    ]

    if all(field in result for field in required_fields):
        is_correct = True

    return is_correct, result

def response_verification_S3(llm_response: str):
    is_correct = False
    result = {}

    match = re.search(r"\{.*\}", llm_response, re.DOTALL)
    if not match:
        return is_correct, result

    json_str = match.group(0)

    try:
        result = json.loads(json_str)
    except json.JSONDecodeError:
        return is_correct, {}

    required_fields = [
        "latest_response",
    ]

    if all(field in result for field in required_fields):
        is_correct = True

    return is_correct, result

class MAS_Attacker:
    def __init__(
        self,
        model:Model,
        scenario:str,
        agent_res_max_retry:int = 3,
        print_agent_prompt:bool = False,
    ) -> None:
        # shared STM
        self.stm = STM()
        # use one model for MAS attacker
        self.model = model
        # MAS
        self.agents:list[SimpleAgent] = []

        sys_promts = [get_S1_AGENT_SYS_PROMPT(scenario=scenario),get_S2_AGENT_SYS_PROMPT(scenario=scenario),get_S3_AGENT_SYS_PROMPT(scenario=scenario)]
        verify_funcs = [response_verification_S1,response_verification_S2,response_verification_S3]
        for i in range(3):
            agent = SimpleAgent(name=f"agent_{i+1}", sys_prompt=sys_promts[i],model=model,max_retry=agent_res_max_retry,verify_func=verify_funcs[i],print_prompt=print_agent_prompt)
            self.agents.append(agent)

    def get_mas_final_response(self,target_query:str) -> str:
        base_user_prompt = self.stm.get_all_STM_for_prompt()
        # A1
        user_prompt_1 = """# Dialogue History:""" + base_user_prompt + """\n# The Latest Response R Generated By the Target Customer Service Agent:\n""" + target_query
        s1_result = self.agents[0].generate_with_llm(user_prompt_1)
        s1_result_str = json.dumps(s1_result, ensure_ascii=False, indent=2)
        print("Agent 1 res")

        # A2
        user_prompt_2 = user_prompt_1 + """\n# The structured dialogue analysis generated by the Interaction Analysis Agent:\n""" + s1_result_str
        s2_result = self.agents[1].generate_with_llm(user_prompt=user_prompt_2)
        print("Agent 2 res")

        # A3
        user_prompt_3 = user_prompt_1 + """\n# The response generation steps designed by the Attack Planning Agent:\n""" + s2_result["final_customer_response_generation_steps"]
        s3_result = self.agents[2].generate_with_llm(user_prompt=user_prompt_3)
        print("Agent 3 res")

        return s3_result["latest_response"]
        